### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by filothei97** [PlanetNull/bithealth#11]
Άλεξ...Βάλε τόνους.....
Και οι άλλοι καλό θα ήταν να συντομεύετε...
Ετελεύτησαν αι ημέραι και πέπει να την παραδώσουμε την εργασία...

**Comment by alexalikiotis** [comment]
τους τονους θα τους βαλει ο @Psycharis  που θα φτιαξει το τελικο pdf @filothei97

**Comment by mikeskaltsou** [comment]
Εγω το commitara...αλεξ σου διορθωσα κατι στο δικο σου αλλα δν εκανα σχολιο γτ δν το εκανα απο το git
