### ISSUE TITLE
Possible adding a new method in Appointment class

### ISSUE THREAD

**Issue by filothei97** [PlanetNull/bithealth#5]
Προτείνω μια νέα μέθοδο η οποία θα σχετίζεται με το ποσό πληρωμής του ραντεβού
Ανάλογα με την ειδικότητα ή ακόμα και default...

**Comment by alexalikiotis** [comment]
Καλη ιδεα !! @filothei97

**Comment by mikeskaltsou** [comment]
ποια ειδικοτητα??? για εξηγησου!

**Comment by mikeskaltsou** [comment]
καλο καιρο εχει σμρ! ΖΗΤΩ Ο ΑΓΓΕΛΟΠΟΥΛΟΣ ΚΑΙ Η ΕΙΡΗΝΗ

**Comment by Psycharis** [comment]
``

**Comment by alexalikiotis** [comment]
I'm on it !

**Comment by alexalikiotis** [comment]
Εκανα αυτο που ηθελες @filothei97 αλλα εβαλε και κατι παραπανω πηγαινενε στο pull request που εκανα να δεις τι αλλαγες προτεινω να κανουμε merge στο develop
